<a href="https://colab.research.google.com/github/chasubeen/ESAA_8th_YB/blob/Week_2/Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

1.22.4


#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
# arr.size * arr.itemsize
# 배열의 크기 * 배열 내의 원소들의 크기

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
a = np.zeros(10) # null vector: 배열의 원소의 값이 0인 배열
a[4] = 5
a

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [14]:
print(arr[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
arr = np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [16]:
arr = np.array([1,2,0,0,4,0])
np.where(arr != 0)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [18]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [21]:
arr = np.random.random([3,3,3])
arr

array([[[0.76018108, 0.43633755, 0.10085277],
        [0.00344645, 0.39641026, 0.62413344],
        [0.3604582 , 0.32038302, 0.4663393 ]],

       [[0.7582239 , 0.17257361, 0.98698083],
        [0.00196959, 0.64488609, 0.46955764],
        [0.64744836, 0.48548342, 0.53785201]],

       [[0.09172517, 0.03407003, 0.64751424],
        [0.42579152, 0.09820731, 0.85971972],
        [0.80980975, 0.41732848, 0.57572657]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [23]:
rand = np.random.random([10,10])
print(rand.min())
print(rand.max())

0.00256585682139554
0.9678847285052748


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [25]:
arr = np.random.random(30)
print(arr.mean())

0.5045957960227595


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [27]:
arr = np.ones([3,5])
arr[1,1:4] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# nan
# False
# False
# nan
# true
# False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [50]:
np.diag([1,2,3,4],k = -1) # k: 주대각선에서 원소들을 어느정도로 이동시킬 것인가

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [45]:
matrix = np.zeros((8,8))
matrix[::2,1:2] = 1
matrix[1::2,::2] = 1 # 1부터 시작해서 끝까지 가는데 2개 간격으로
matrix

array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [49]:
np.unravel_index(99,(6,7,8))  # 100번째 원소의 인덱스: 99
# unravel_index(): 인덱스 배열 반환
# 6행 7열 8면의 3차원 배열에서 index 99에 해당하는 원소의 위치 

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [33]:
rand = np.random.random((5,5))
norm = (rand - rand.mean()) / rand.std()
norm

array([[-1.36076275, -0.86071899, -0.53978588,  0.93034694, -1.34812781],
       [-0.7065006 , -0.2344256 , -0.77759553,  0.71437364,  0.55489733],
       [ 0.67953252, -0.26873341,  1.20193018,  0.51851658,  1.91548141],
       [-1.3837102 , -1.04806654, -0.55230479,  1.79653799, -1.22779224],
       [-0.54057858,  0.81730869, -0.42761641,  1.20961622,  0.93817783]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [35]:
color = np.dtype([("r",np.ubyte), # np.ubyte: unsigned byte(자료형)
                  ("g",np.ubyte),
                  ("b",np.ubyte),
                  ("a",np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [43]:
np.random.random(1)

array([0.2344998])

In [36]:
arr1 = np.random.random((5,3))
arr2 = np.random.random((3,2))
np.dot(arr1,arr2)

array([[1.4547434 , 0.83839229],
       [1.22953912, 1.20537875],
       [1.22771572, 0.90132415],
       [1.21966439, 1.1875268 ],
       [1.30599297, 0.88033711]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [38]:
arr = np.arange(11)
arr[(2<arr) & (arr <9)] *= -1 # boolean indexing
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [55]:
for i in range(5):
  print(i)

0
1
2
3
4


In [39]:
print(sum(range(5),-1)) # sum((숫자), -1): -1부터 시작해서 5개의 수를 더한다. 
from numpy import * 
print(sum(range(5),-1)) # np.sum((숫자),-1): 여기서 -1은 축을 지정하는 것이다. 

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [56]:
# j: 복소수

z = np.arange(10)
print(z**z) # 가능
print(2 << z >> 2) # 가능(쉬프트 연산자)
print(z <- z) # 가능
print(1j*z) # 가능
print(z/1/1) # 가능
print(z<z>z) # 불가능

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: ignored

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [44]:
# arr의 경우 나누기가 불가능하다.
np.array(0) / np.array(0)

<ipython-input-44-c4a8ba250ced>:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [46]:
# 몫만 구하는 것은 가능하다.
np.array(0) // np.array(0)

<ipython-input-46-bbc4a20aca0c>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [48]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3