<a href="https://colab.research.google.com/github/chasubeen/ESAA_8th_YB/blob/Week_2/Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.22.4


#### 3. Create a null vector of size 10 (★☆☆)

- null vector: 모든 원소가 0인 벡터
- ```np.zeros(n)```: 모든 원소가 0인 크기 n의 array 생성

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

- 배열의 메모리 크기
  - 배열의 크기(arr.size) * 배열 내 각 원소의 byte 크기(arr.itemsize)

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
a = np.zeros(10) # null vector: 배열의 원소의 값이 0인 배열
a[4] = 5
a

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

- 인덱싱을 통해 배열 내의 특정 원소의 값을 변경할 수 있다.

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

- ```np.arange(start = 0, stop, step)```
  - start부터 (stop - 1)까지의 값을 순차적으로 ndarray 값으로 반환

In [6]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
print(arr[::-1]) # 내림차순 정렬

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
arr = np.arange(0,9) # 1차원 배열 생성
arr.reshape(3,3) # 3x3의 2차원 배열로

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

- ```np.where(조건식)```
  - 조건에 해당하는 원소가 위치하는 인덱스 반환
- ```np.nonzero(배열)```
  - 배열 내 원소들 중 0이 아닌 원소의 위치 반환

In [9]:
arr = np.array([1,2,0,0,4,0])
np.where(arr != 0)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

- ```np.eye(n)```
  - n x n의 identity matrix 생성

In [10]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

- ```numpy.random.random(size)```
  - numpy의 random 모듈 안의 random 함수
  - [0.0, 1.0) 구간에서 난수 발생

In [11]:
arr = np.random.random([3,3,3])
arr

array([[[0.53373537, 0.46841463, 0.86423489],
        [0.07929042, 0.57081879, 0.40767353],
        [0.91479135, 0.22834758, 0.80988675]],

       [[0.05386595, 0.3684818 , 0.1547544 ],
        [0.27429474, 0.10914382, 0.22853842],
        [0.16214348, 0.06740927, 0.03852341]],

       [[0.36215825, 0.42410554, 0.98199147],
        [0.00193404, 0.27659887, 0.82499048],
        [0.65196215, 0.12464823, 0.75805707]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [12]:
rand = np.random.random([10,10])
print(rand.min())
print(rand.max())

0.00918959427596766
0.9984713449507434


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [13]:
arr = np.random.random(30)
print(arr.mean())

0.5357890078978819


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

- ```np.ones((nrows, ncols), dtype = float64)```
  - 튜플 형태의 shape값 입력 시 모든 값을 1로 채운 해당 shape를 가진 ndarray 반환

In [14]:
arr = np.ones([3,5])
arr[1,1:4] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [15]:
# nan
# False
# False
# nan
# true
# False

- nan과의 수치 연산 시 결과는 무조건 nan으로 나온다. 


#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

- ```np.diag(arr, k = 0)```
  - 주어진 원소들로 대각행렬을 생성하는 함수
  - k: 주대각선을 기준으로 대각성분들을 어떻게 이동시킬 것인가.
    - k > 0: 주대각선 윗부분으로
    - k < 0: 주대각선 아랫부분으로 

In [16]:
np.diag([1,2,3,4],k = -1) # k: 주대각선에서 원소들을 어느정도로 이동시킬 것인가

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [17]:
matrix = np.zeros((8,8))
matrix[::2,1:2] = 1
matrix[1::2,::2] = 1 # 1부터 시작해서 끝까지 가는데 2개 간격으로
matrix

array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

- ```matrix[start:end:step]```
  - start부터 end 이전까지 주어진 step마다 이동

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

- ```np.unravel_index(indices, shape)```  
  - 1열을 가진 flat index나 array를 튜플 형태로 주어진 shape로 변환
  - 해당하는 위치 반환

In [18]:
np.unravel_index(99,(6,7,8))  # 100번째 원소의 인덱스: 99
# unravel_index(): 인덱스 배열 반환
# 6행 7열 8면의 3차원 배열에서 index 99에 해당하는 원소의 위치 

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [19]:
rand = np.random.random((5,5))
norm = (rand - rand.mean()) / rand.std()
norm

array([[ 1.31515811e+00,  8.82110921e-01, -4.04563765e-01,
        -2.36593853e+00, -4.28513863e-01],
       [-1.15130541e+00, -7.72778498e-01, -2.37712624e-01,
         3.78310030e-01, -1.17269557e+00],
       [ 1.33627528e+00, -1.07832395e+00,  1.30400065e-01,
         1.34036328e+00,  1.27254096e+00],
       [-1.55654126e+00, -9.48429329e-04,  8.58154520e-01,
         5.59367530e-01,  7.00128153e-01],
       [-1.75885555e-01,  1.05326443e+00,  8.35374761e-01,
        -6.87058404e-01, -6.29182174e-01]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

- ```np.dtype()```  
  - data type 객체를 생성하는 함수
- ```np.ubyte```  
  - unsigned integer type

In [20]:
color = np.dtype([("r",np.ubyte), # np.ubyte: unsigned byte(자료형)
                  ("g",np.ubyte),
                  ("b",np.ubyte),
                  ("a",np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

- ```np.dot(matrix1, matrix2)```  
  - 두 행렬의 행렬곱을 계산해주는 함수
- ```@ 연산자```  
  - np.dot()과 동일한 연산 수행

In [21]:
np.random.random(1)

array([0.73396971])

In [22]:
arr1 = np.random.random((5,3))
arr2 = np.random.random((3,2))
np.dot(arr1,arr2)

array([[0.77090064, 0.78455127],
       [0.6939612 , 0.77788036],
       [0.5359662 , 0.58001956],
       [1.15974012, 1.20437068],
       [0.49228527, 0.54047391]])

#### 22. Given a 1D array, negate(음수화) all elements which are between 3 and 8, in place. (★☆☆)

In [23]:
arr = np.arange(11)
arr[(2<arr) & (arr <9)] *= -1 # boolean indexing
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [24]:
print(sum(range(5),-1)) 
# sum((숫자), -1): -1부터 시작해서 5까지의(5는 포함 x) 정수를 더한다. 

from numpy import * 

print(sum(range(5),-1)) 
# np.sum((숫자),-1): 여기서 -1은 축을 지정하는 것이다. 

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

- numpy의 ```>>```, ```<<``` 연산자
  - shift bit 연산자
  - ex> 2 << z: z = z * 2 ^ z  

In [26]:
# j: 복소수

z = np.arange(10)
print(z**z) # 가능
print(2 << z >> 2) # 가능(쉬프트 연산자)
print(z <- z) # 가능
print(1j*z) # 가능
print(z/1/1) # 가능
print(z<z>z) # 불가능

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: ignored

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
# arr의 경우 나누기가 불가능하다.
# nan을 리턴함

np.array(0) / np.array(0)

<ipython-input-27-9697840a5f24>:4: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [28]:
# 몫만 구하는 것은 가능하다.

np.array(0) // np.array(0)

<ipython-input-28-a5bff53b8941>:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [29]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

- ```np.intersect1d(arr1, arr2)```  
  - arr1, arr2 내의 원소들 중 공통 원소 추출

In [30]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[1 7 1 0 1 0 8 5 0 5]
[5 8 1 3 5 9 1 6 7 1]
[1 5 7 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

- np.sqrt(n): 제곱근을 구할 때 n이 음수인 경우 제대로 된 결과값을 계산하지 못한다.
- np.emath.sqrt(n): 조금 더 복잡한 계산도 수행할 수 있다.

In [31]:
import numpy as np

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-32-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [33]:
Z = np.arange('2016-07','2016-08',dtype = 'datetime64[D]')

- 7월과 8월 사이를 dtype = 'datetime64[D]'로 나누어 일별로 분류

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

- ```np.add()```: 더하기
- ```np.divide()```: 나누기
- ```np.negative()```: 양수 -> 음수, 음수 -> 양수
- ```np.multiply()```: 곱하기
- ```out``` 매개변수의 역할: 계산 결과를 어느 행렬에 덮어쓸 것인가

In [34]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3

np.add(A,B,out = B) # A와 B의 합을 계산한 결과를 B에 저장
np.divide(A,2,out = A)
np.negative(A,out = A)
np.multiply(A,B,out = A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [35]:
Z = np.random.uniform(0,10,10)
 
print(Z - Z%1) # Z에서 Z를1로 나눈 나머지를 빼서 정수 부분을 구함
print(np.floor(Z)) # 내림
print(np.ceil(Z)) # 올림
print(Z.astype(int)) # integer로 형변환 
print(np.trunc(Z)) # 소수점 아래 부분 절사

[5. 4. 4. 4. 5. 3. 8. 3. 3. 5.]
[5. 4. 4. 4. 5. 3. 8. 3. 3. 5.]
[6. 5. 5. 5. 6. 4. 9. 4. 4. 6.]
[5 4 4 4 5 3 8 3 3 5]
[5. 4. 4. 4. 5. 3. 8. 3. 3. 5.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [36]:
Z = np.zeros((5,5)) # null matrix
Z += np.arange(5) # 하나씩 더해주기
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 32. Create a random vector of size 10 and sort it (★★☆)

- ```np.sort()```  
  - 원래 행렬은 그대로 유지한 채 원본 행렬의 정렬된 행렬을 반환
- ```ndarray.sort()```
  - 원래 행렬 자체를 정렬한 형태로 반환

In [37]:
arr = np.random.random(10)
print(arr)

arr.sort()
arr

[0.77283416 0.49450833 0.7472642  0.35514326 0.54473211 0.77100491
 0.12821619 0.24541382 0.9211495  0.38505238]


array([0.12821619, 0.24541382, 0.35514326, 0.38505238, 0.49450833,
       0.54473211, 0.7472642 , 0.77100491, 0.77283416, 0.9211495 ])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

- ```np.random.randint(start, end, n)```: start에서 end 사이의 수들로 지정된 개수의 난수 발생
- ```np.array_equal(A,B)```: 두 개의 배열이 같은 지 비교 

In [38]:
np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates(데카르트 좌표계), convert them to polar coordinates(극좌표계) (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

- ```np.sqrt()```: 제곱근 함수
- ```np.arctan2(X,Y)```: 역탄젠트 함수 

In [39]:
arr = np.random.random((10,2))
X,Y = arr[:,0], arr[:,1]

R = np.sqrt(X**2 + Y ** 2) # 원점(0,0)에서 해당 점까지의 거리
P = np.arctan2(Y,X) # 극좌표계로 변환

print(R)
print(P)

[0.47556597 0.27880904 1.16590371 0.93948377 0.92059989 0.76502974
 1.30252915 0.89094984 1.09460703 0.49205789]
[0.27378851 0.36140704 0.73940457 0.44949622 0.51180954 1.52952786
 0.78580447 0.39282282 0.68273183 1.48201915]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

- ```ndarray.argmax()```: ndarray에서 가장 큰 값을 가지는 원소의 인덱스 값을 반환

In [41]:
z = np.random.random(10)
print(z)
print()
z[z.argmax()] = 0
print(z)

[0.17206855 0.07191628 0.79999882 0.88528673 0.88079511 0.49147094
 0.2049784  0.87841917 0.60258926 0.57386256]

[0.17206855 0.07191628 0.79999882 0.         0.88079511 0.49147094
 0.2049784  0.87841917 0.60258926 0.57386256]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

- ```ndarray.argmin()```: ndarray에서 가장 작은 값을 가지는 원소의 인덱스 값을 반환

In [52]:
Z = np.arange(100)
v = np.random.uniform(0,100)
r = np.abs(Z-v)
Z[r.argmin()]

65

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

- ```numpy.ndenumerate()```: 다차원 배열의 index와 value 반환
- ```numpy.ndindex()```: 다차원 index 반환

In [53]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
  print(index, value)

for index in np.ndindex(Z.shape):
  print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

- ```np.put(arr,ind,value)```: arr내의 원소들 중 ind에 해당하는 위치의 원소들의 값을 value로 변경

In [55]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),4)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 4. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [57]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()]) # 행의 컬럼 1의 성분의 크기를 보고 순서대로 정렬한다.

[[5 7 8]
 [0 3 5]
 [8 3 1]]
[[0 3 5]
 [8 3 1]
 [5 7 8]]
